---
name: PullHero Assisted Documentation workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use for the documentation update'
        required: false
        default: 'main'

jobs:
  pullhero-document:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        #with:
        #  persist-credentials: false
        #  ref: ${{ github.event.issue.pull_request.head.ref }}
        #  repository: ${{ github.repository }}

      - name: Show Repository and Branch Info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.event.inputs.branch || 'main' }}"

      - name: Debug Secret Variables
        run: |
          echo "Verifying Secret Variables..."
          if [[ -z "${{ secrets.OPENAI_API_KEY }}" ]]; then
            echo "ERROR: OPENAI_API_KEY is missing!"
          else
            echo "OPENAI_API_KEY is set. (Length: ${#OPENAI_API_KEY})"
          fi
          if [[ -z "${{ secrets.GITHUB_TOKEN }}" ]]; then
            echo "ERROR: GITHUB_TOKEN is missing!"
          else
            echo "GITHUB_TOKEN is set. (Length: ${#GITHUB_TOKEN})"
          fi
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PullHero documentation agent
        #uses: pullhero/agent@v1
        uses: ./
        with:
          vcs-token: "${{ secrets.GITHUB_TOKEN }}"
          agent: "document"
          agent-action: "review"
          llm-api-key: "${{ secrets.OPENAI_API_KEY }}"
          llm-api-host: "api.openai.com"
          llm-api-model: "gpt-4o-mini"
